services:
  - type: web
    name: edviron-backend
    env: node
    plan: free
    buildCommand: npm run render-build
    startCommand: npm run render-start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5173
      - key: NODE_VERSION
        value: 18
    healthCheckPath: /api/health